SELECT * FROM [MyAppDb].[dbo].[AspNetUserRoles]
SELECT * FROM  [dbo].[__EFMigrationsHistory]
SELECT * FROM  [dbo].[AspNetRoleClaims]
SELECT * FROM  [dbo].[AspNetRoles]
SELECT * FROM  [dbo].[AspNetUserLogins]
SELECT * FROM  [dbo].[AspNetUserRoles]
SELECT * FROM  [dbo].[AspNetUsers]
SELECT * FROM  [dbo].[AspNetUserTokens]m
SELECT * FROM  [dbo].[DeviceCodes]
SELECT * FROM  [dbo].[Keys]
SELECT * FROM  [dbo].[PersistedGrants]
SELECT * FROM  [dbo].[AspNetRoleClaims]
SELECT *  FROM [MyAppDb].[dbo].[TodoLists]
SELECT * FROM  dbo.TodoItems
